# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/trevorw/projects/Minder

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/trevorw/projects/Minder

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/trevorw/projects/Minder/CMakeFiles /home/trevorw/projects/Minder/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/trevorw/projects/Minder/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named com.github.phase1geo.Minder

# Build rule for target.
com.github.phase1geo.Minder: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 com.github.phase1geo.Minder
.PHONY : com.github.phase1geo.Minder

# fast build rule for target.
com.github.phase1geo.Minder/fast:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/build
.PHONY : com.github.phase1geo.Minder/fast

#=============================================================================
# Target rules for targets named po

# Build rule for target.
po: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 po
.PHONY : po

# fast build rule for target.
po/fast:
	$(MAKE) -f po/CMakeFiles/po.dir/build.make po/CMakeFiles/po.dir/build
.PHONY : po/fast

#=============================================================================
# Target rules for targets named i18n

# Build rule for target.
i18n: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 i18n
.PHONY : i18n

# fast build rule for target.
i18n/fast:
	$(MAKE) -f po/CMakeFiles/i18n.dir/build.make po/CMakeFiles/i18n.dir/build
.PHONY : i18n/fast

#=============================================================================
# Target rules for targets named pot

# Build rule for target.
pot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pot
.PHONY : pot

# fast build rule for target.
pot/fast:
	$(MAKE) -f po/CMakeFiles/pot.dir/build.make po/CMakeFiles/pot.dir/build
.PHONY : pot/fast

src/document.o: src/document.c.o

.PHONY : src/document.o

# target to build an object file
src/document.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/document.c.o
.PHONY : src/document.c.o

src/document.i: src/document.c.i

.PHONY : src/document.i

# target to preprocess a source file
src/document.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/document.c.i
.PHONY : src/document.c.i

src/document.s: src/document.c.s

.PHONY : src/document.s

# target to generate assembly for a file
src/document.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/document.c.s
.PHONY : src/document.c.s

src/draw_area.o: src/draw_area.c.o

.PHONY : src/draw_area.o

# target to build an object file
src/draw_area.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/draw_area.c.o
.PHONY : src/draw_area.c.o

src/draw_area.i: src/draw_area.c.i

.PHONY : src/draw_area.i

# target to preprocess a source file
src/draw_area.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/draw_area.c.i
.PHONY : src/draw_area.c.i

src/draw_area.s: src/draw_area.c.s

.PHONY : src/draw_area.s

# target to generate assembly for a file
src/draw_area.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/draw_area.c.s
.PHONY : src/draw_area.c.s

src/layout.o: src/layout.c.o

.PHONY : src/layout.o

# target to build an object file
src/layout.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/layout.c.o
.PHONY : src/layout.c.o

src/layout.i: src/layout.c.i

.PHONY : src/layout.i

# target to preprocess a source file
src/layout.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/layout.c.i
.PHONY : src/layout.c.i

src/layout.s: src/layout.c.s

.PHONY : src/layout.s

# target to generate assembly for a file
src/layout.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/layout.c.s
.PHONY : src/layout.c.s

src/layout_inspector.o: src/layout_inspector.c.o

.PHONY : src/layout_inspector.o

# target to build an object file
src/layout_inspector.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/layout_inspector.c.o
.PHONY : src/layout_inspector.c.o

src/layout_inspector.i: src/layout_inspector.c.i

.PHONY : src/layout_inspector.i

# target to preprocess a source file
src/layout_inspector.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/layout_inspector.c.i
.PHONY : src/layout_inspector.c.i

src/layout_inspector.s: src/layout_inspector.c.s

.PHONY : src/layout_inspector.s

# target to generate assembly for a file
src/layout_inspector.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/layout_inspector.c.s
.PHONY : src/layout_inspector.c.s

src/main_window.o: src/main_window.c.o

.PHONY : src/main_window.o

# target to build an object file
src/main_window.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/main_window.c.o
.PHONY : src/main_window.c.o

src/main_window.i: src/main_window.c.i

.PHONY : src/main_window.i

# target to preprocess a source file
src/main_window.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/main_window.c.i
.PHONY : src/main_window.c.i

src/main_window.s: src/main_window.c.s

.PHONY : src/main_window.s

# target to generate assembly for a file
src/main_window.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/main_window.c.s
.PHONY : src/main_window.c.s

src/minder.o: src/minder.c.o

.PHONY : src/minder.o

# target to build an object file
src/minder.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/minder.c.o
.PHONY : src/minder.c.o

src/minder.i: src/minder.c.i

.PHONY : src/minder.i

# target to preprocess a source file
src/minder.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/minder.c.i
.PHONY : src/minder.c.i

src/minder.s: src/minder.c.s

.PHONY : src/minder.s

# target to generate assembly for a file
src/minder.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/minder.c.s
.PHONY : src/minder.c.s

src/node.o: src/node.c.o

.PHONY : src/node.o

# target to build an object file
src/node.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/node.c.o
.PHONY : src/node.c.o

src/node.i: src/node.c.i

.PHONY : src/node.i

# target to preprocess a source file
src/node.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/node.c.i
.PHONY : src/node.c.i

src/node.s: src/node.c.s

.PHONY : src/node.s

# target to generate assembly for a file
src/node.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/node.c.s
.PHONY : src/node.c.s

src/node_inspector.o: src/node_inspector.c.o

.PHONY : src/node_inspector.o

# target to build an object file
src/node_inspector.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/node_inspector.c.o
.PHONY : src/node_inspector.c.o

src/node_inspector.i: src/node_inspector.c.i

.PHONY : src/node_inspector.i

# target to preprocess a source file
src/node_inspector.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/node_inspector.c.i
.PHONY : src/node_inspector.c.i

src/node_inspector.s: src/node_inspector.c.s

.PHONY : src/node_inspector.s

# target to generate assembly for a file
src/node_inspector.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/node_inspector.c.s
.PHONY : src/node_inspector.c.s

src/nonroot_node.o: src/nonroot_node.c.o

.PHONY : src/nonroot_node.o

# target to build an object file
src/nonroot_node.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/nonroot_node.c.o
.PHONY : src/nonroot_node.c.o

src/nonroot_node.i: src/nonroot_node.c.i

.PHONY : src/nonroot_node.i

# target to preprocess a source file
src/nonroot_node.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/nonroot_node.c.i
.PHONY : src/nonroot_node.c.i

src/nonroot_node.s: src/nonroot_node.c.s

.PHONY : src/nonroot_node.s

# target to generate assembly for a file
src/nonroot_node.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/nonroot_node.c.s
.PHONY : src/nonroot_node.c.s

src/root_node.o: src/root_node.c.o

.PHONY : src/root_node.o

# target to build an object file
src/root_node.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/root_node.c.o
.PHONY : src/root_node.c.o

src/root_node.i: src/root_node.c.i

.PHONY : src/root_node.i

# target to preprocess a source file
src/root_node.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/root_node.c.i
.PHONY : src/root_node.c.i

src/root_node.s: src/root_node.c.s

.PHONY : src/root_node.s

# target to generate assembly for a file
src/root_node.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/root_node.c.s
.PHONY : src/root_node.c.s

src/theme.o: src/theme.c.o

.PHONY : src/theme.o

# target to build an object file
src/theme.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/theme.c.o
.PHONY : src/theme.c.o

src/theme.i: src/theme.c.i

.PHONY : src/theme.i

# target to preprocess a source file
src/theme.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/theme.c.i
.PHONY : src/theme.c.i

src/theme.s: src/theme.c.s

.PHONY : src/theme.s

# target to generate assembly for a file
src/theme.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/theme.c.s
.PHONY : src/theme.c.s

src/theme_default.o: src/theme_default.c.o

.PHONY : src/theme_default.o

# target to build an object file
src/theme_default.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/theme_default.c.o
.PHONY : src/theme_default.c.o

src/theme_default.i: src/theme_default.c.i

.PHONY : src/theme_default.i

# target to preprocess a source file
src/theme_default.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/theme_default.c.i
.PHONY : src/theme_default.c.i

src/theme_default.s: src/theme_default.c.s

.PHONY : src/theme_default.s

# target to generate assembly for a file
src/theme_default.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/theme_default.c.s
.PHONY : src/theme_default.c.s

src/theme_inspector.o: src/theme_inspector.c.o

.PHONY : src/theme_inspector.o

# target to build an object file
src/theme_inspector.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/theme_inspector.c.o
.PHONY : src/theme_inspector.c.o

src/theme_inspector.i: src/theme_inspector.c.i

.PHONY : src/theme_inspector.i

# target to preprocess a source file
src/theme_inspector.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/theme_inspector.c.i
.PHONY : src/theme_inspector.c.i

src/theme_inspector.s: src/theme_inspector.c.s

.PHONY : src/theme_inspector.s

# target to generate assembly for a file
src/theme_inspector.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/theme_inspector.c.s
.PHONY : src/theme_inspector.c.s

src/undo_buffer.o: src/undo_buffer.c.o

.PHONY : src/undo_buffer.o

# target to build an object file
src/undo_buffer.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/undo_buffer.c.o
.PHONY : src/undo_buffer.c.o

src/undo_buffer.i: src/undo_buffer.c.i

.PHONY : src/undo_buffer.i

# target to preprocess a source file
src/undo_buffer.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/undo_buffer.c.i
.PHONY : src/undo_buffer.c.i

src/undo_buffer.s: src/undo_buffer.c.s

.PHONY : src/undo_buffer.s

# target to generate assembly for a file
src/undo_buffer.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/undo_buffer.c.s
.PHONY : src/undo_buffer.c.s

src/undo_item.o: src/undo_item.c.o

.PHONY : src/undo_item.o

# target to build an object file
src/undo_item.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/undo_item.c.o
.PHONY : src/undo_item.c.o

src/undo_item.i: src/undo_item.c.i

.PHONY : src/undo_item.i

# target to preprocess a source file
src/undo_item.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/undo_item.c.i
.PHONY : src/undo_item.c.i

src/undo_item.s: src/undo_item.c.s

.PHONY : src/undo_item.s

# target to generate assembly for a file
src/undo_item.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/undo_item.c.s
.PHONY : src/undo_item.c.s

src/undo_node_delete.o: src/undo_node_delete.c.o

.PHONY : src/undo_node_delete.o

# target to build an object file
src/undo_node_delete.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/undo_node_delete.c.o
.PHONY : src/undo_node_delete.c.o

src/undo_node_delete.i: src/undo_node_delete.c.i

.PHONY : src/undo_node_delete.i

# target to preprocess a source file
src/undo_node_delete.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/undo_node_delete.c.i
.PHONY : src/undo_node_delete.c.i

src/undo_node_delete.s: src/undo_node_delete.c.s

.PHONY : src/undo_node_delete.s

# target to generate assembly for a file
src/undo_node_delete.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/undo_node_delete.c.s
.PHONY : src/undo_node_delete.c.s

src/undo_node_fold.o: src/undo_node_fold.c.o

.PHONY : src/undo_node_fold.o

# target to build an object file
src/undo_node_fold.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/undo_node_fold.c.o
.PHONY : src/undo_node_fold.c.o

src/undo_node_fold.i: src/undo_node_fold.c.i

.PHONY : src/undo_node_fold.i

# target to preprocess a source file
src/undo_node_fold.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/undo_node_fold.c.i
.PHONY : src/undo_node_fold.c.i

src/undo_node_fold.s: src/undo_node_fold.c.s

.PHONY : src/undo_node_fold.s

# target to generate assembly for a file
src/undo_node_fold.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/undo_node_fold.c.s
.PHONY : src/undo_node_fold.c.s

src/undo_node_insert.o: src/undo_node_insert.c.o

.PHONY : src/undo_node_insert.o

# target to build an object file
src/undo_node_insert.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/undo_node_insert.c.o
.PHONY : src/undo_node_insert.c.o

src/undo_node_insert.i: src/undo_node_insert.c.i

.PHONY : src/undo_node_insert.i

# target to preprocess a source file
src/undo_node_insert.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/undo_node_insert.c.i
.PHONY : src/undo_node_insert.c.i

src/undo_node_insert.s: src/undo_node_insert.c.s

.PHONY : src/undo_node_insert.s

# target to generate assembly for a file
src/undo_node_insert.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/undo_node_insert.c.s
.PHONY : src/undo_node_insert.c.s

src/undo_node_name.o: src/undo_node_name.c.o

.PHONY : src/undo_node_name.o

# target to build an object file
src/undo_node_name.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/undo_node_name.c.o
.PHONY : src/undo_node_name.c.o

src/undo_node_name.i: src/undo_node_name.c.i

.PHONY : src/undo_node_name.i

# target to preprocess a source file
src/undo_node_name.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/undo_node_name.c.i
.PHONY : src/undo_node_name.c.i

src/undo_node_name.s: src/undo_node_name.c.s

.PHONY : src/undo_node_name.s

# target to generate assembly for a file
src/undo_node_name.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/undo_node_name.c.s
.PHONY : src/undo_node_name.c.s

src/undo_node_note.o: src/undo_node_note.c.o

.PHONY : src/undo_node_note.o

# target to build an object file
src/undo_node_note.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/undo_node_note.c.o
.PHONY : src/undo_node_note.c.o

src/undo_node_note.i: src/undo_node_note.c.i

.PHONY : src/undo_node_note.i

# target to preprocess a source file
src/undo_node_note.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/undo_node_note.c.i
.PHONY : src/undo_node_note.c.i

src/undo_node_note.s: src/undo_node_note.c.s

.PHONY : src/undo_node_note.s

# target to generate assembly for a file
src/undo_node_note.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/undo_node_note.c.s
.PHONY : src/undo_node_note.c.s

src/undo_node_task.o: src/undo_node_task.c.o

.PHONY : src/undo_node_task.o

# target to build an object file
src/undo_node_task.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/undo_node_task.c.o
.PHONY : src/undo_node_task.c.o

src/undo_node_task.i: src/undo_node_task.c.i

.PHONY : src/undo_node_task.i

# target to preprocess a source file
src/undo_node_task.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/undo_node_task.c.i
.PHONY : src/undo_node_task.c.i

src/undo_node_task.s: src/undo_node_task.c.s

.PHONY : src/undo_node_task.s

# target to generate assembly for a file
src/undo_node_task.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.Minder.dir/build.make CMakeFiles/com.github.phase1geo.Minder.dir/src/undo_node_task.c.s
.PHONY : src/undo_node_task.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... com.github.phase1geo.Minder"
	@echo "... edit_cache"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... po"
	@echo "... i18n"
	@echo "... pot"
	@echo "... src/document.o"
	@echo "... src/document.i"
	@echo "... src/document.s"
	@echo "... src/draw_area.o"
	@echo "... src/draw_area.i"
	@echo "... src/draw_area.s"
	@echo "... src/layout.o"
	@echo "... src/layout.i"
	@echo "... src/layout.s"
	@echo "... src/layout_inspector.o"
	@echo "... src/layout_inspector.i"
	@echo "... src/layout_inspector.s"
	@echo "... src/main_window.o"
	@echo "... src/main_window.i"
	@echo "... src/main_window.s"
	@echo "... src/minder.o"
	@echo "... src/minder.i"
	@echo "... src/minder.s"
	@echo "... src/node.o"
	@echo "... src/node.i"
	@echo "... src/node.s"
	@echo "... src/node_inspector.o"
	@echo "... src/node_inspector.i"
	@echo "... src/node_inspector.s"
	@echo "... src/nonroot_node.o"
	@echo "... src/nonroot_node.i"
	@echo "... src/nonroot_node.s"
	@echo "... src/root_node.o"
	@echo "... src/root_node.i"
	@echo "... src/root_node.s"
	@echo "... src/theme.o"
	@echo "... src/theme.i"
	@echo "... src/theme.s"
	@echo "... src/theme_default.o"
	@echo "... src/theme_default.i"
	@echo "... src/theme_default.s"
	@echo "... src/theme_inspector.o"
	@echo "... src/theme_inspector.i"
	@echo "... src/theme_inspector.s"
	@echo "... src/undo_buffer.o"
	@echo "... src/undo_buffer.i"
	@echo "... src/undo_buffer.s"
	@echo "... src/undo_item.o"
	@echo "... src/undo_item.i"
	@echo "... src/undo_item.s"
	@echo "... src/undo_node_delete.o"
	@echo "... src/undo_node_delete.i"
	@echo "... src/undo_node_delete.s"
	@echo "... src/undo_node_fold.o"
	@echo "... src/undo_node_fold.i"
	@echo "... src/undo_node_fold.s"
	@echo "... src/undo_node_insert.o"
	@echo "... src/undo_node_insert.i"
	@echo "... src/undo_node_insert.s"
	@echo "... src/undo_node_name.o"
	@echo "... src/undo_node_name.i"
	@echo "... src/undo_node_name.s"
	@echo "... src/undo_node_note.o"
	@echo "... src/undo_node_note.i"
	@echo "... src/undo_node_note.s"
	@echo "... src/undo_node_task.o"
	@echo "... src/undo_node_task.i"
	@echo "... src/undo_node_task.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

