# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/trevorw/projects/Minder

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/trevorw/projects/Minder

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/trevorw/projects/Minder/CMakeFiles /home/trevorw/projects/Minder/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/trevorw/projects/Minder/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named com.github.phase1geo.minder

# Build rule for target.
com.github.phase1geo.minder: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 com.github.phase1geo.minder
.PHONY : com.github.phase1geo.minder

# fast build rule for target.
com.github.phase1geo.minder/fast:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/build
.PHONY : com.github.phase1geo.minder/fast

#=============================================================================
# Target rules for targets named po

# Build rule for target.
po: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 po
.PHONY : po

# fast build rule for target.
po/fast:
	$(MAKE) -f po/CMakeFiles/po.dir/build.make po/CMakeFiles/po.dir/build
.PHONY : po/fast

#=============================================================================
# Target rules for targets named i18n

# Build rule for target.
i18n: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 i18n
.PHONY : i18n

# fast build rule for target.
i18n/fast:
	$(MAKE) -f po/CMakeFiles/i18n.dir/build.make po/CMakeFiles/i18n.dir/build
.PHONY : i18n/fast

#=============================================================================
# Target rules for targets named pot

# Build rule for target.
pot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pot
.PHONY : pot

# fast build rule for target.
pot/fast:
	$(MAKE) -f po/CMakeFiles/pot.dir/build.make po/CMakeFiles/pot.dir/build
.PHONY : pot/fast

src/Animator.o: src/Animator.c.o

.PHONY : src/Animator.o

# target to build an object file
src/Animator.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Animator.c.o
.PHONY : src/Animator.c.o

src/Animator.i: src/Animator.c.i

.PHONY : src/Animator.i

# target to preprocess a source file
src/Animator.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Animator.c.i
.PHONY : src/Animator.c.i

src/Animator.s: src/Animator.c.s

.PHONY : src/Animator.s

# target to generate assembly for a file
src/Animator.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Animator.c.s
.PHONY : src/Animator.c.s

src/Application.o: src/Application.c.o

.PHONY : src/Application.o

# target to build an object file
src/Application.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Application.c.o
.PHONY : src/Application.c.o

src/Application.i: src/Application.c.i

.PHONY : src/Application.i

# target to preprocess a source file
src/Application.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Application.c.i
.PHONY : src/Application.c.i

src/Application.s: src/Application.c.s

.PHONY : src/Application.s

# target to generate assembly for a file
src/Application.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Application.c.s
.PHONY : src/Application.c.s

src/Document.o: src/Document.c.o

.PHONY : src/Document.o

# target to build an object file
src/Document.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Document.c.o
.PHONY : src/Document.c.o

src/Document.i: src/Document.c.i

.PHONY : src/Document.i

# target to preprocess a source file
src/Document.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Document.c.i
.PHONY : src/Document.c.i

src/Document.s: src/Document.c.s

.PHONY : src/Document.s

# target to generate assembly for a file
src/Document.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Document.c.s
.PHONY : src/Document.c.s

src/DrawArea.o: src/DrawArea.c.o

.PHONY : src/DrawArea.o

# target to build an object file
src/DrawArea.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/DrawArea.c.o
.PHONY : src/DrawArea.c.o

src/DrawArea.i: src/DrawArea.c.i

.PHONY : src/DrawArea.i

# target to preprocess a source file
src/DrawArea.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/DrawArea.c.i
.PHONY : src/DrawArea.c.i

src/DrawArea.s: src/DrawArea.c.s

.PHONY : src/DrawArea.s

# target to generate assembly for a file
src/DrawArea.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/DrawArea.c.s
.PHONY : src/DrawArea.c.s

src/Layout.o: src/Layout.c.o

.PHONY : src/Layout.o

# target to build an object file
src/Layout.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Layout.c.o
.PHONY : src/Layout.c.o

src/Layout.i: src/Layout.c.i

.PHONY : src/Layout.i

# target to preprocess a source file
src/Layout.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Layout.c.i
.PHONY : src/Layout.c.i

src/Layout.s: src/Layout.c.s

.PHONY : src/Layout.s

# target to generate assembly for a file
src/Layout.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Layout.c.s
.PHONY : src/Layout.c.s

src/Layouts.o: src/Layouts.c.o

.PHONY : src/Layouts.o

# target to build an object file
src/Layouts.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Layouts.c.o
.PHONY : src/Layouts.c.o

src/Layouts.i: src/Layouts.c.i

.PHONY : src/Layouts.i

# target to preprocess a source file
src/Layouts.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Layouts.c.i
.PHONY : src/Layouts.c.i

src/Layouts.s: src/Layouts.c.s

.PHONY : src/Layouts.s

# target to generate assembly for a file
src/Layouts.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Layouts.c.s
.PHONY : src/Layouts.c.s

src/MainWindow.o: src/MainWindow.c.o

.PHONY : src/MainWindow.o

# target to build an object file
src/MainWindow.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/MainWindow.c.o
.PHONY : src/MainWindow.c.o

src/MainWindow.i: src/MainWindow.c.i

.PHONY : src/MainWindow.i

# target to preprocess a source file
src/MainWindow.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/MainWindow.c.i
.PHONY : src/MainWindow.c.i

src/MainWindow.s: src/MainWindow.c.s

.PHONY : src/MainWindow.s

# target to generate assembly for a file
src/MainWindow.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/MainWindow.c.s
.PHONY : src/MainWindow.c.s

src/MapInspector.o: src/MapInspector.c.o

.PHONY : src/MapInspector.o

# target to build an object file
src/MapInspector.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/MapInspector.c.o
.PHONY : src/MapInspector.c.o

src/MapInspector.i: src/MapInspector.c.i

.PHONY : src/MapInspector.i

# target to preprocess a source file
src/MapInspector.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/MapInspector.c.i
.PHONY : src/MapInspector.c.i

src/MapInspector.s: src/MapInspector.c.s

.PHONY : src/MapInspector.s

# target to generate assembly for a file
src/MapInspector.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/MapInspector.c.s
.PHONY : src/MapInspector.c.s

src/Node.o: src/Node.c.o

.PHONY : src/Node.o

# target to build an object file
src/Node.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Node.c.o
.PHONY : src/Node.c.o

src/Node.i: src/Node.c.i

.PHONY : src/Node.i

# target to preprocess a source file
src/Node.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Node.c.i
.PHONY : src/Node.c.i

src/Node.s: src/Node.c.s

.PHONY : src/Node.s

# target to generate assembly for a file
src/Node.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Node.c.s
.PHONY : src/Node.c.s

src/NodeInspector.o: src/NodeInspector.c.o

.PHONY : src/NodeInspector.o

# target to build an object file
src/NodeInspector.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/NodeInspector.c.o
.PHONY : src/NodeInspector.c.o

src/NodeInspector.i: src/NodeInspector.c.i

.PHONY : src/NodeInspector.i

# target to preprocess a source file
src/NodeInspector.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/NodeInspector.c.i
.PHONY : src/NodeInspector.c.i

src/NodeInspector.s: src/NodeInspector.c.s

.PHONY : src/NodeInspector.s

# target to generate assembly for a file
src/NodeInspector.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/NodeInspector.c.s
.PHONY : src/NodeInspector.c.s

src/NonrootNode.o: src/NonrootNode.c.o

.PHONY : src/NonrootNode.o

# target to build an object file
src/NonrootNode.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/NonrootNode.c.o
.PHONY : src/NonrootNode.c.o

src/NonrootNode.i: src/NonrootNode.c.i

.PHONY : src/NonrootNode.i

# target to preprocess a source file
src/NonrootNode.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/NonrootNode.c.i
.PHONY : src/NonrootNode.c.i

src/NonrootNode.s: src/NonrootNode.c.s

.PHONY : src/NonrootNode.s

# target to generate assembly for a file
src/NonrootNode.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/NonrootNode.c.s
.PHONY : src/NonrootNode.c.s

src/OPML.o: src/OPML.c.o

.PHONY : src/OPML.o

# target to build an object file
src/OPML.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/OPML.c.o
.PHONY : src/OPML.c.o

src/OPML.i: src/OPML.c.i

.PHONY : src/OPML.i

# target to preprocess a source file
src/OPML.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/OPML.c.i
.PHONY : src/OPML.c.i

src/OPML.s: src/OPML.c.s

.PHONY : src/OPML.s

# target to generate assembly for a file
src/OPML.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/OPML.c.s
.PHONY : src/OPML.c.s

src/PDF.o: src/PDF.c.o

.PHONY : src/PDF.o

# target to build an object file
src/PDF.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/PDF.c.o
.PHONY : src/PDF.c.o

src/PDF.i: src/PDF.c.i

.PHONY : src/PDF.i

# target to preprocess a source file
src/PDF.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/PDF.c.i
.PHONY : src/PDF.c.i

src/PDF.s: src/PDF.c.s

.PHONY : src/PDF.s

# target to generate assembly for a file
src/PDF.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/PDF.c.s
.PHONY : src/PDF.c.s

src/Partitioner.o: src/Partitioner.c.o

.PHONY : src/Partitioner.o

# target to build an object file
src/Partitioner.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Partitioner.c.o
.PHONY : src/Partitioner.c.o

src/Partitioner.i: src/Partitioner.c.i

.PHONY : src/Partitioner.i

# target to preprocess a source file
src/Partitioner.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Partitioner.c.i
.PHONY : src/Partitioner.c.i

src/Partitioner.s: src/Partitioner.c.s

.PHONY : src/Partitioner.s

# target to generate assembly for a file
src/Partitioner.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Partitioner.c.s
.PHONY : src/Partitioner.c.s

src/Print.o: src/Print.c.o

.PHONY : src/Print.o

# target to build an object file
src/Print.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Print.c.o
.PHONY : src/Print.c.o

src/Print.i: src/Print.c.i

.PHONY : src/Print.i

# target to preprocess a source file
src/Print.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Print.c.i
.PHONY : src/Print.c.i

src/Print.s: src/Print.c.s

.PHONY : src/Print.s

# target to generate assembly for a file
src/Print.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Print.c.s
.PHONY : src/Print.c.s

src/RootNode.o: src/RootNode.c.o

.PHONY : src/RootNode.o

# target to build an object file
src/RootNode.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/RootNode.c.o
.PHONY : src/RootNode.c.o

src/RootNode.i: src/RootNode.c.i

.PHONY : src/RootNode.i

# target to preprocess a source file
src/RootNode.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/RootNode.c.i
.PHONY : src/RootNode.c.i

src/RootNode.s: src/RootNode.c.s

.PHONY : src/RootNode.s

# target to generate assembly for a file
src/RootNode.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/RootNode.c.s
.PHONY : src/RootNode.c.s

src/Theme.o: src/Theme.c.o

.PHONY : src/Theme.o

# target to build an object file
src/Theme.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Theme.c.o
.PHONY : src/Theme.c.o

src/Theme.i: src/Theme.c.i

.PHONY : src/Theme.i

# target to preprocess a source file
src/Theme.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Theme.c.i
.PHONY : src/Theme.c.i

src/Theme.s: src/Theme.c.s

.PHONY : src/Theme.s

# target to generate assembly for a file
src/Theme.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Theme.c.s
.PHONY : src/Theme.c.s

src/Themes.o: src/Themes.c.o

.PHONY : src/Themes.o

# target to build an object file
src/Themes.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Themes.c.o
.PHONY : src/Themes.c.o

src/Themes.i: src/Themes.c.i

.PHONY : src/Themes.i

# target to preprocess a source file
src/Themes.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Themes.c.i
.PHONY : src/Themes.c.i

src/Themes.s: src/Themes.c.s

.PHONY : src/Themes.s

# target to generate assembly for a file
src/Themes.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/Themes.c.s
.PHONY : src/Themes.c.s

src/UndoBuffer.o: src/UndoBuffer.c.o

.PHONY : src/UndoBuffer.o

# target to build an object file
src/UndoBuffer.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/UndoBuffer.c.o
.PHONY : src/UndoBuffer.c.o

src/UndoBuffer.i: src/UndoBuffer.c.i

.PHONY : src/UndoBuffer.i

# target to preprocess a source file
src/UndoBuffer.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/UndoBuffer.c.i
.PHONY : src/UndoBuffer.c.i

src/UndoBuffer.s: src/UndoBuffer.c.s

.PHONY : src/UndoBuffer.s

# target to generate assembly for a file
src/UndoBuffer.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/UndoBuffer.c.s
.PHONY : src/UndoBuffer.c.s

src/UndoItem.o: src/UndoItem.c.o

.PHONY : src/UndoItem.o

# target to build an object file
src/UndoItem.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/UndoItem.c.o
.PHONY : src/UndoItem.c.o

src/UndoItem.i: src/UndoItem.c.i

.PHONY : src/UndoItem.i

# target to preprocess a source file
src/UndoItem.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/UndoItem.c.i
.PHONY : src/UndoItem.c.i

src/UndoItem.s: src/UndoItem.c.s

.PHONY : src/UndoItem.s

# target to generate assembly for a file
src/UndoItem.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/UndoItem.c.s
.PHONY : src/UndoItem.c.s

src/animator/AnimatorAction.o: src/animator/AnimatorAction.c.o

.PHONY : src/animator/AnimatorAction.o

# target to build an object file
src/animator/AnimatorAction.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/animator/AnimatorAction.c.o
.PHONY : src/animator/AnimatorAction.c.o

src/animator/AnimatorAction.i: src/animator/AnimatorAction.c.i

.PHONY : src/animator/AnimatorAction.i

# target to preprocess a source file
src/animator/AnimatorAction.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/animator/AnimatorAction.c.i
.PHONY : src/animator/AnimatorAction.c.i

src/animator/AnimatorAction.s: src/animator/AnimatorAction.c.s

.PHONY : src/animator/AnimatorAction.s

# target to generate assembly for a file
src/animator/AnimatorAction.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/animator/AnimatorAction.c.s
.PHONY : src/animator/AnimatorAction.c.s

src/animator/AnimatorNodes.o: src/animator/AnimatorNodes.c.o

.PHONY : src/animator/AnimatorNodes.o

# target to build an object file
src/animator/AnimatorNodes.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/animator/AnimatorNodes.c.o
.PHONY : src/animator/AnimatorNodes.c.o

src/animator/AnimatorNodes.i: src/animator/AnimatorNodes.c.i

.PHONY : src/animator/AnimatorNodes.i

# target to preprocess a source file
src/animator/AnimatorNodes.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/animator/AnimatorNodes.c.i
.PHONY : src/animator/AnimatorNodes.c.i

src/animator/AnimatorNodes.s: src/animator/AnimatorNodes.c.s

.PHONY : src/animator/AnimatorNodes.s

# target to generate assembly for a file
src/animator/AnimatorNodes.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/animator/AnimatorNodes.c.s
.PHONY : src/animator/AnimatorNodes.c.s

src/animator/AnimatorPan.o: src/animator/AnimatorPan.c.o

.PHONY : src/animator/AnimatorPan.o

# target to build an object file
src/animator/AnimatorPan.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/animator/AnimatorPan.c.o
.PHONY : src/animator/AnimatorPan.c.o

src/animator/AnimatorPan.i: src/animator/AnimatorPan.c.i

.PHONY : src/animator/AnimatorPan.i

# target to preprocess a source file
src/animator/AnimatorPan.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/animator/AnimatorPan.c.i
.PHONY : src/animator/AnimatorPan.c.i

src/animator/AnimatorPan.s: src/animator/AnimatorPan.c.s

.PHONY : src/animator/AnimatorPan.s

# target to generate assembly for a file
src/animator/AnimatorPan.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/animator/AnimatorPan.c.s
.PHONY : src/animator/AnimatorPan.c.s

src/animator/AnimatorPositions.o: src/animator/AnimatorPositions.c.o

.PHONY : src/animator/AnimatorPositions.o

# target to build an object file
src/animator/AnimatorPositions.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/animator/AnimatorPositions.c.o
.PHONY : src/animator/AnimatorPositions.c.o

src/animator/AnimatorPositions.i: src/animator/AnimatorPositions.c.i

.PHONY : src/animator/AnimatorPositions.i

# target to preprocess a source file
src/animator/AnimatorPositions.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/animator/AnimatorPositions.c.i
.PHONY : src/animator/AnimatorPositions.c.i

src/animator/AnimatorPositions.s: src/animator/AnimatorPositions.c.s

.PHONY : src/animator/AnimatorPositions.s

# target to generate assembly for a file
src/animator/AnimatorPositions.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/animator/AnimatorPositions.c.s
.PHONY : src/animator/AnimatorPositions.c.s

src/animator/AnimatorScale.o: src/animator/AnimatorScale.c.o

.PHONY : src/animator/AnimatorScale.o

# target to build an object file
src/animator/AnimatorScale.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/animator/AnimatorScale.c.o
.PHONY : src/animator/AnimatorScale.c.o

src/animator/AnimatorScale.i: src/animator/AnimatorScale.c.i

.PHONY : src/animator/AnimatorScale.i

# target to preprocess a source file
src/animator/AnimatorScale.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/animator/AnimatorScale.c.i
.PHONY : src/animator/AnimatorScale.c.i

src/animator/AnimatorScale.s: src/animator/AnimatorScale.c.s

.PHONY : src/animator/AnimatorScale.s

# target to generate assembly for a file
src/animator/AnimatorScale.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/animator/AnimatorScale.c.s
.PHONY : src/animator/AnimatorScale.c.s

src/layouts/LayoutDown.o: src/layouts/LayoutDown.c.o

.PHONY : src/layouts/LayoutDown.o

# target to build an object file
src/layouts/LayoutDown.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/layouts/LayoutDown.c.o
.PHONY : src/layouts/LayoutDown.c.o

src/layouts/LayoutDown.i: src/layouts/LayoutDown.c.i

.PHONY : src/layouts/LayoutDown.i

# target to preprocess a source file
src/layouts/LayoutDown.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/layouts/LayoutDown.c.i
.PHONY : src/layouts/LayoutDown.c.i

src/layouts/LayoutDown.s: src/layouts/LayoutDown.c.s

.PHONY : src/layouts/LayoutDown.s

# target to generate assembly for a file
src/layouts/LayoutDown.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/layouts/LayoutDown.c.s
.PHONY : src/layouts/LayoutDown.c.s

src/layouts/LayoutHorizontal.o: src/layouts/LayoutHorizontal.c.o

.PHONY : src/layouts/LayoutHorizontal.o

# target to build an object file
src/layouts/LayoutHorizontal.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/layouts/LayoutHorizontal.c.o
.PHONY : src/layouts/LayoutHorizontal.c.o

src/layouts/LayoutHorizontal.i: src/layouts/LayoutHorizontal.c.i

.PHONY : src/layouts/LayoutHorizontal.i

# target to preprocess a source file
src/layouts/LayoutHorizontal.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/layouts/LayoutHorizontal.c.i
.PHONY : src/layouts/LayoutHorizontal.c.i

src/layouts/LayoutHorizontal.s: src/layouts/LayoutHorizontal.c.s

.PHONY : src/layouts/LayoutHorizontal.s

# target to generate assembly for a file
src/layouts/LayoutHorizontal.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/layouts/LayoutHorizontal.c.s
.PHONY : src/layouts/LayoutHorizontal.c.s

src/layouts/LayoutLeft.o: src/layouts/LayoutLeft.c.o

.PHONY : src/layouts/LayoutLeft.o

# target to build an object file
src/layouts/LayoutLeft.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/layouts/LayoutLeft.c.o
.PHONY : src/layouts/LayoutLeft.c.o

src/layouts/LayoutLeft.i: src/layouts/LayoutLeft.c.i

.PHONY : src/layouts/LayoutLeft.i

# target to preprocess a source file
src/layouts/LayoutLeft.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/layouts/LayoutLeft.c.i
.PHONY : src/layouts/LayoutLeft.c.i

src/layouts/LayoutLeft.s: src/layouts/LayoutLeft.c.s

.PHONY : src/layouts/LayoutLeft.s

# target to generate assembly for a file
src/layouts/LayoutLeft.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/layouts/LayoutLeft.c.s
.PHONY : src/layouts/LayoutLeft.c.s

src/layouts/LayoutManual.o: src/layouts/LayoutManual.c.o

.PHONY : src/layouts/LayoutManual.o

# target to build an object file
src/layouts/LayoutManual.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/layouts/LayoutManual.c.o
.PHONY : src/layouts/LayoutManual.c.o

src/layouts/LayoutManual.i: src/layouts/LayoutManual.c.i

.PHONY : src/layouts/LayoutManual.i

# target to preprocess a source file
src/layouts/LayoutManual.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/layouts/LayoutManual.c.i
.PHONY : src/layouts/LayoutManual.c.i

src/layouts/LayoutManual.s: src/layouts/LayoutManual.c.s

.PHONY : src/layouts/LayoutManual.s

# target to generate assembly for a file
src/layouts/LayoutManual.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/layouts/LayoutManual.c.s
.PHONY : src/layouts/LayoutManual.c.s

src/layouts/LayoutRight.o: src/layouts/LayoutRight.c.o

.PHONY : src/layouts/LayoutRight.o

# target to build an object file
src/layouts/LayoutRight.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/layouts/LayoutRight.c.o
.PHONY : src/layouts/LayoutRight.c.o

src/layouts/LayoutRight.i: src/layouts/LayoutRight.c.i

.PHONY : src/layouts/LayoutRight.i

# target to preprocess a source file
src/layouts/LayoutRight.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/layouts/LayoutRight.c.i
.PHONY : src/layouts/LayoutRight.c.i

src/layouts/LayoutRight.s: src/layouts/LayoutRight.c.s

.PHONY : src/layouts/LayoutRight.s

# target to generate assembly for a file
src/layouts/LayoutRight.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/layouts/LayoutRight.c.s
.PHONY : src/layouts/LayoutRight.c.s

src/layouts/LayoutUp.o: src/layouts/LayoutUp.c.o

.PHONY : src/layouts/LayoutUp.o

# target to build an object file
src/layouts/LayoutUp.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/layouts/LayoutUp.c.o
.PHONY : src/layouts/LayoutUp.c.o

src/layouts/LayoutUp.i: src/layouts/LayoutUp.c.i

.PHONY : src/layouts/LayoutUp.i

# target to preprocess a source file
src/layouts/LayoutUp.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/layouts/LayoutUp.c.i
.PHONY : src/layouts/LayoutUp.c.i

src/layouts/LayoutUp.s: src/layouts/LayoutUp.c.s

.PHONY : src/layouts/LayoutUp.s

# target to generate assembly for a file
src/layouts/LayoutUp.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/layouts/LayoutUp.c.s
.PHONY : src/layouts/LayoutUp.c.s

src/layouts/LayoutVertical.o: src/layouts/LayoutVertical.c.o

.PHONY : src/layouts/LayoutVertical.o

# target to build an object file
src/layouts/LayoutVertical.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/layouts/LayoutVertical.c.o
.PHONY : src/layouts/LayoutVertical.c.o

src/layouts/LayoutVertical.i: src/layouts/LayoutVertical.c.i

.PHONY : src/layouts/LayoutVertical.i

# target to preprocess a source file
src/layouts/LayoutVertical.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/layouts/LayoutVertical.c.i
.PHONY : src/layouts/LayoutVertical.c.i

src/layouts/LayoutVertical.s: src/layouts/LayoutVertical.c.s

.PHONY : src/layouts/LayoutVertical.s

# target to generate assembly for a file
src/layouts/LayoutVertical.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/layouts/LayoutVertical.c.s
.PHONY : src/layouts/LayoutVertical.c.s

src/themes/ThemeDark.o: src/themes/ThemeDark.c.o

.PHONY : src/themes/ThemeDark.o

# target to build an object file
src/themes/ThemeDark.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/themes/ThemeDark.c.o
.PHONY : src/themes/ThemeDark.c.o

src/themes/ThemeDark.i: src/themes/ThemeDark.c.i

.PHONY : src/themes/ThemeDark.i

# target to preprocess a source file
src/themes/ThemeDark.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/themes/ThemeDark.c.i
.PHONY : src/themes/ThemeDark.c.i

src/themes/ThemeDark.s: src/themes/ThemeDark.c.s

.PHONY : src/themes/ThemeDark.s

# target to generate assembly for a file
src/themes/ThemeDark.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/themes/ThemeDark.c.s
.PHONY : src/themes/ThemeDark.c.s

src/themes/ThemeDefault.o: src/themes/ThemeDefault.c.o

.PHONY : src/themes/ThemeDefault.o

# target to build an object file
src/themes/ThemeDefault.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/themes/ThemeDefault.c.o
.PHONY : src/themes/ThemeDefault.c.o

src/themes/ThemeDefault.i: src/themes/ThemeDefault.c.i

.PHONY : src/themes/ThemeDefault.i

# target to preprocess a source file
src/themes/ThemeDefault.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/themes/ThemeDefault.c.i
.PHONY : src/themes/ThemeDefault.c.i

src/themes/ThemeDefault.s: src/themes/ThemeDefault.c.s

.PHONY : src/themes/ThemeDefault.s

# target to generate assembly for a file
src/themes/ThemeDefault.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/themes/ThemeDefault.c.s
.PHONY : src/themes/ThemeDefault.c.s

src/undo_actions/UndoNodeAttach.o: src/undo_actions/UndoNodeAttach.c.o

.PHONY : src/undo_actions/UndoNodeAttach.o

# target to build an object file
src/undo_actions/UndoNodeAttach.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/undo_actions/UndoNodeAttach.c.o
.PHONY : src/undo_actions/UndoNodeAttach.c.o

src/undo_actions/UndoNodeAttach.i: src/undo_actions/UndoNodeAttach.c.i

.PHONY : src/undo_actions/UndoNodeAttach.i

# target to preprocess a source file
src/undo_actions/UndoNodeAttach.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/undo_actions/UndoNodeAttach.c.i
.PHONY : src/undo_actions/UndoNodeAttach.c.i

src/undo_actions/UndoNodeAttach.s: src/undo_actions/UndoNodeAttach.c.s

.PHONY : src/undo_actions/UndoNodeAttach.s

# target to generate assembly for a file
src/undo_actions/UndoNodeAttach.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/undo_actions/UndoNodeAttach.c.s
.PHONY : src/undo_actions/UndoNodeAttach.c.s

src/undo_actions/UndoNodeDelete.o: src/undo_actions/UndoNodeDelete.c.o

.PHONY : src/undo_actions/UndoNodeDelete.o

# target to build an object file
src/undo_actions/UndoNodeDelete.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/undo_actions/UndoNodeDelete.c.o
.PHONY : src/undo_actions/UndoNodeDelete.c.o

src/undo_actions/UndoNodeDelete.i: src/undo_actions/UndoNodeDelete.c.i

.PHONY : src/undo_actions/UndoNodeDelete.i

# target to preprocess a source file
src/undo_actions/UndoNodeDelete.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/undo_actions/UndoNodeDelete.c.i
.PHONY : src/undo_actions/UndoNodeDelete.c.i

src/undo_actions/UndoNodeDelete.s: src/undo_actions/UndoNodeDelete.c.s

.PHONY : src/undo_actions/UndoNodeDelete.s

# target to generate assembly for a file
src/undo_actions/UndoNodeDelete.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/undo_actions/UndoNodeDelete.c.s
.PHONY : src/undo_actions/UndoNodeDelete.c.s

src/undo_actions/UndoNodeDetach.o: src/undo_actions/UndoNodeDetach.c.o

.PHONY : src/undo_actions/UndoNodeDetach.o

# target to build an object file
src/undo_actions/UndoNodeDetach.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/undo_actions/UndoNodeDetach.c.o
.PHONY : src/undo_actions/UndoNodeDetach.c.o

src/undo_actions/UndoNodeDetach.i: src/undo_actions/UndoNodeDetach.c.i

.PHONY : src/undo_actions/UndoNodeDetach.i

# target to preprocess a source file
src/undo_actions/UndoNodeDetach.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/undo_actions/UndoNodeDetach.c.i
.PHONY : src/undo_actions/UndoNodeDetach.c.i

src/undo_actions/UndoNodeDetach.s: src/undo_actions/UndoNodeDetach.c.s

.PHONY : src/undo_actions/UndoNodeDetach.s

# target to generate assembly for a file
src/undo_actions/UndoNodeDetach.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/undo_actions/UndoNodeDetach.c.s
.PHONY : src/undo_actions/UndoNodeDetach.c.s

src/undo_actions/UndoNodeFold.o: src/undo_actions/UndoNodeFold.c.o

.PHONY : src/undo_actions/UndoNodeFold.o

# target to build an object file
src/undo_actions/UndoNodeFold.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/undo_actions/UndoNodeFold.c.o
.PHONY : src/undo_actions/UndoNodeFold.c.o

src/undo_actions/UndoNodeFold.i: src/undo_actions/UndoNodeFold.c.i

.PHONY : src/undo_actions/UndoNodeFold.i

# target to preprocess a source file
src/undo_actions/UndoNodeFold.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/undo_actions/UndoNodeFold.c.i
.PHONY : src/undo_actions/UndoNodeFold.c.i

src/undo_actions/UndoNodeFold.s: src/undo_actions/UndoNodeFold.c.s

.PHONY : src/undo_actions/UndoNodeFold.s

# target to generate assembly for a file
src/undo_actions/UndoNodeFold.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/undo_actions/UndoNodeFold.c.s
.PHONY : src/undo_actions/UndoNodeFold.c.s

src/undo_actions/UndoNodeInsert.o: src/undo_actions/UndoNodeInsert.c.o

.PHONY : src/undo_actions/UndoNodeInsert.o

# target to build an object file
src/undo_actions/UndoNodeInsert.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/undo_actions/UndoNodeInsert.c.o
.PHONY : src/undo_actions/UndoNodeInsert.c.o

src/undo_actions/UndoNodeInsert.i: src/undo_actions/UndoNodeInsert.c.i

.PHONY : src/undo_actions/UndoNodeInsert.i

# target to preprocess a source file
src/undo_actions/UndoNodeInsert.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/undo_actions/UndoNodeInsert.c.i
.PHONY : src/undo_actions/UndoNodeInsert.c.i

src/undo_actions/UndoNodeInsert.s: src/undo_actions/UndoNodeInsert.c.s

.PHONY : src/undo_actions/UndoNodeInsert.s

# target to generate assembly for a file
src/undo_actions/UndoNodeInsert.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/undo_actions/UndoNodeInsert.c.s
.PHONY : src/undo_actions/UndoNodeInsert.c.s

src/undo_actions/UndoNodeMove.o: src/undo_actions/UndoNodeMove.c.o

.PHONY : src/undo_actions/UndoNodeMove.o

# target to build an object file
src/undo_actions/UndoNodeMove.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/undo_actions/UndoNodeMove.c.o
.PHONY : src/undo_actions/UndoNodeMove.c.o

src/undo_actions/UndoNodeMove.i: src/undo_actions/UndoNodeMove.c.i

.PHONY : src/undo_actions/UndoNodeMove.i

# target to preprocess a source file
src/undo_actions/UndoNodeMove.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/undo_actions/UndoNodeMove.c.i
.PHONY : src/undo_actions/UndoNodeMove.c.i

src/undo_actions/UndoNodeMove.s: src/undo_actions/UndoNodeMove.c.s

.PHONY : src/undo_actions/UndoNodeMove.s

# target to generate assembly for a file
src/undo_actions/UndoNodeMove.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/undo_actions/UndoNodeMove.c.s
.PHONY : src/undo_actions/UndoNodeMove.c.s

src/undo_actions/UndoNodeName.o: src/undo_actions/UndoNodeName.c.o

.PHONY : src/undo_actions/UndoNodeName.o

# target to build an object file
src/undo_actions/UndoNodeName.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/undo_actions/UndoNodeName.c.o
.PHONY : src/undo_actions/UndoNodeName.c.o

src/undo_actions/UndoNodeName.i: src/undo_actions/UndoNodeName.c.i

.PHONY : src/undo_actions/UndoNodeName.i

# target to preprocess a source file
src/undo_actions/UndoNodeName.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/undo_actions/UndoNodeName.c.i
.PHONY : src/undo_actions/UndoNodeName.c.i

src/undo_actions/UndoNodeName.s: src/undo_actions/UndoNodeName.c.s

.PHONY : src/undo_actions/UndoNodeName.s

# target to generate assembly for a file
src/undo_actions/UndoNodeName.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/undo_actions/UndoNodeName.c.s
.PHONY : src/undo_actions/UndoNodeName.c.s

src/undo_actions/UndoNodeNote.o: src/undo_actions/UndoNodeNote.c.o

.PHONY : src/undo_actions/UndoNodeNote.o

# target to build an object file
src/undo_actions/UndoNodeNote.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/undo_actions/UndoNodeNote.c.o
.PHONY : src/undo_actions/UndoNodeNote.c.o

src/undo_actions/UndoNodeNote.i: src/undo_actions/UndoNodeNote.c.i

.PHONY : src/undo_actions/UndoNodeNote.i

# target to preprocess a source file
src/undo_actions/UndoNodeNote.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/undo_actions/UndoNodeNote.c.i
.PHONY : src/undo_actions/UndoNodeNote.c.i

src/undo_actions/UndoNodeNote.s: src/undo_actions/UndoNodeNote.c.s

.PHONY : src/undo_actions/UndoNodeNote.s

# target to generate assembly for a file
src/undo_actions/UndoNodeNote.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/undo_actions/UndoNodeNote.c.s
.PHONY : src/undo_actions/UndoNodeNote.c.s

src/undo_actions/UndoNodeTask.o: src/undo_actions/UndoNodeTask.c.o

.PHONY : src/undo_actions/UndoNodeTask.o

# target to build an object file
src/undo_actions/UndoNodeTask.c.o:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/undo_actions/UndoNodeTask.c.o
.PHONY : src/undo_actions/UndoNodeTask.c.o

src/undo_actions/UndoNodeTask.i: src/undo_actions/UndoNodeTask.c.i

.PHONY : src/undo_actions/UndoNodeTask.i

# target to preprocess a source file
src/undo_actions/UndoNodeTask.c.i:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/undo_actions/UndoNodeTask.c.i
.PHONY : src/undo_actions/UndoNodeTask.c.i

src/undo_actions/UndoNodeTask.s: src/undo_actions/UndoNodeTask.c.s

.PHONY : src/undo_actions/UndoNodeTask.s

# target to generate assembly for a file
src/undo_actions/UndoNodeTask.c.s:
	$(MAKE) -f CMakeFiles/com.github.phase1geo.minder.dir/build.make CMakeFiles/com.github.phase1geo.minder.dir/src/undo_actions/UndoNodeTask.c.s
.PHONY : src/undo_actions/UndoNodeTask.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... com.github.phase1geo.minder"
	@echo "... edit_cache"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... po"
	@echo "... i18n"
	@echo "... pot"
	@echo "... src/Animator.o"
	@echo "... src/Animator.i"
	@echo "... src/Animator.s"
	@echo "... src/Application.o"
	@echo "... src/Application.i"
	@echo "... src/Application.s"
	@echo "... src/Document.o"
	@echo "... src/Document.i"
	@echo "... src/Document.s"
	@echo "... src/DrawArea.o"
	@echo "... src/DrawArea.i"
	@echo "... src/DrawArea.s"
	@echo "... src/Layout.o"
	@echo "... src/Layout.i"
	@echo "... src/Layout.s"
	@echo "... src/Layouts.o"
	@echo "... src/Layouts.i"
	@echo "... src/Layouts.s"
	@echo "... src/MainWindow.o"
	@echo "... src/MainWindow.i"
	@echo "... src/MainWindow.s"
	@echo "... src/MapInspector.o"
	@echo "... src/MapInspector.i"
	@echo "... src/MapInspector.s"
	@echo "... src/Node.o"
	@echo "... src/Node.i"
	@echo "... src/Node.s"
	@echo "... src/NodeInspector.o"
	@echo "... src/NodeInspector.i"
	@echo "... src/NodeInspector.s"
	@echo "... src/NonrootNode.o"
	@echo "... src/NonrootNode.i"
	@echo "... src/NonrootNode.s"
	@echo "... src/OPML.o"
	@echo "... src/OPML.i"
	@echo "... src/OPML.s"
	@echo "... src/PDF.o"
	@echo "... src/PDF.i"
	@echo "... src/PDF.s"
	@echo "... src/Partitioner.o"
	@echo "... src/Partitioner.i"
	@echo "... src/Partitioner.s"
	@echo "... src/Print.o"
	@echo "... src/Print.i"
	@echo "... src/Print.s"
	@echo "... src/RootNode.o"
	@echo "... src/RootNode.i"
	@echo "... src/RootNode.s"
	@echo "... src/Theme.o"
	@echo "... src/Theme.i"
	@echo "... src/Theme.s"
	@echo "... src/Themes.o"
	@echo "... src/Themes.i"
	@echo "... src/Themes.s"
	@echo "... src/UndoBuffer.o"
	@echo "... src/UndoBuffer.i"
	@echo "... src/UndoBuffer.s"
	@echo "... src/UndoItem.o"
	@echo "... src/UndoItem.i"
	@echo "... src/UndoItem.s"
	@echo "... src/animator/AnimatorAction.o"
	@echo "... src/animator/AnimatorAction.i"
	@echo "... src/animator/AnimatorAction.s"
	@echo "... src/animator/AnimatorNodes.o"
	@echo "... src/animator/AnimatorNodes.i"
	@echo "... src/animator/AnimatorNodes.s"
	@echo "... src/animator/AnimatorPan.o"
	@echo "... src/animator/AnimatorPan.i"
	@echo "... src/animator/AnimatorPan.s"
	@echo "... src/animator/AnimatorPositions.o"
	@echo "... src/animator/AnimatorPositions.i"
	@echo "... src/animator/AnimatorPositions.s"
	@echo "... src/animator/AnimatorScale.o"
	@echo "... src/animator/AnimatorScale.i"
	@echo "... src/animator/AnimatorScale.s"
	@echo "... src/layouts/LayoutDown.o"
	@echo "... src/layouts/LayoutDown.i"
	@echo "... src/layouts/LayoutDown.s"
	@echo "... src/layouts/LayoutHorizontal.o"
	@echo "... src/layouts/LayoutHorizontal.i"
	@echo "... src/layouts/LayoutHorizontal.s"
	@echo "... src/layouts/LayoutLeft.o"
	@echo "... src/layouts/LayoutLeft.i"
	@echo "... src/layouts/LayoutLeft.s"
	@echo "... src/layouts/LayoutManual.o"
	@echo "... src/layouts/LayoutManual.i"
	@echo "... src/layouts/LayoutManual.s"
	@echo "... src/layouts/LayoutRight.o"
	@echo "... src/layouts/LayoutRight.i"
	@echo "... src/layouts/LayoutRight.s"
	@echo "... src/layouts/LayoutUp.o"
	@echo "... src/layouts/LayoutUp.i"
	@echo "... src/layouts/LayoutUp.s"
	@echo "... src/layouts/LayoutVertical.o"
	@echo "... src/layouts/LayoutVertical.i"
	@echo "... src/layouts/LayoutVertical.s"
	@echo "... src/themes/ThemeDark.o"
	@echo "... src/themes/ThemeDark.i"
	@echo "... src/themes/ThemeDark.s"
	@echo "... src/themes/ThemeDefault.o"
	@echo "... src/themes/ThemeDefault.i"
	@echo "... src/themes/ThemeDefault.s"
	@echo "... src/undo_actions/UndoNodeAttach.o"
	@echo "... src/undo_actions/UndoNodeAttach.i"
	@echo "... src/undo_actions/UndoNodeAttach.s"
	@echo "... src/undo_actions/UndoNodeDelete.o"
	@echo "... src/undo_actions/UndoNodeDelete.i"
	@echo "... src/undo_actions/UndoNodeDelete.s"
	@echo "... src/undo_actions/UndoNodeDetach.o"
	@echo "... src/undo_actions/UndoNodeDetach.i"
	@echo "... src/undo_actions/UndoNodeDetach.s"
	@echo "... src/undo_actions/UndoNodeFold.o"
	@echo "... src/undo_actions/UndoNodeFold.i"
	@echo "... src/undo_actions/UndoNodeFold.s"
	@echo "... src/undo_actions/UndoNodeInsert.o"
	@echo "... src/undo_actions/UndoNodeInsert.i"
	@echo "... src/undo_actions/UndoNodeInsert.s"
	@echo "... src/undo_actions/UndoNodeMove.o"
	@echo "... src/undo_actions/UndoNodeMove.i"
	@echo "... src/undo_actions/UndoNodeMove.s"
	@echo "... src/undo_actions/UndoNodeName.o"
	@echo "... src/undo_actions/UndoNodeName.i"
	@echo "... src/undo_actions/UndoNodeName.s"
	@echo "... src/undo_actions/UndoNodeNote.o"
	@echo "... src/undo_actions/UndoNodeNote.i"
	@echo "... src/undo_actions/UndoNodeNote.s"
	@echo "... src/undo_actions/UndoNodeTask.o"
	@echo "... src/undo_actions/UndoNodeTask.i"
	@echo "... src/undo_actions/UndoNodeTask.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

