/* minder.c generated by valac 0.36.12, the Vala compiler
 * generated from minder.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <glib/gi18n-lib.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_MINDER (minder_get_type ())
#define MINDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MINDER, Minder))
#define MINDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MINDER, MinderClass))
#define IS_MINDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MINDER))
#define IS_MINDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MINDER))
#define MINDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MINDER, MinderClass))

typedef struct _Minder Minder;
typedef struct _MinderClass MinderClass;
typedef struct _MinderPrivate MinderPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _Minder {
	GtkApplication parent_instance;
	MinderPrivate * priv;
};

struct _MinderClass {
	GtkApplicationClass parent_class;
};


static gpointer minder_parent_class = NULL;

GType minder_get_type (void) G_GNUC_CONST;
enum  {
	MINDER_0_PROPERTY
};
Minder* minder_new (void);
Minder* minder_construct (GType object_type);
static void minder_real_activate (GApplication* base);
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self);
gint minder_main (gchar** args, int args_length1);


Minder* minder_construct (GType object_type) {
	Minder * self = NULL;
#line 6 "/home/trevorw/projects/Minder/src/minder.vala"
	self = (Minder*) g_object_new (object_type, "application-id", "com.github.phase1geo.Minder", "flags", G_APPLICATION_FLAGS_NONE, NULL);
#line 5 "/home/trevorw/projects/Minder/src/minder.vala"
	return self;
#line 56 "minder.c"
}


Minder* minder_new (void) {
#line 5 "/home/trevorw/projects/Minder/src/minder.vala"
	return minder_construct (TYPE_MINDER);
#line 63 "minder.c"
}


static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
#line 22 "/home/trevorw/projects/Minder/src/minder.vala"
	gtk_main_quit ();
#line 70 "minder.c"
}


static void minder_real_activate (GApplication* base) {
	Minder * self;
	GtkHeaderBar* header = NULL;
	GtkHeaderBar* _tmp0_;
	GtkApplicationWindow* app_window = NULL;
	GtkApplicationWindow* _tmp1_;
	GtkBox* box = NULL;
	GtkBox* _tmp2_;
#line 9 "/home/trevorw/projects/Minder/src/minder.vala"
	self = (Minder*) base;
#line 11 "/home/trevorw/projects/Minder/src/minder.vala"
	_tmp0_ = (GtkHeaderBar*) gtk_header_bar_new ();
#line 11 "/home/trevorw/projects/Minder/src/minder.vala"
	g_object_ref_sink (_tmp0_);
#line 11 "/home/trevorw/projects/Minder/src/minder.vala"
	header = _tmp0_;
#line 12 "/home/trevorw/projects/Minder/src/minder.vala"
	gtk_header_bar_set_title (header, _ ("Minder"));
#line 13 "/home/trevorw/projects/Minder/src/minder.vala"
	gtk_header_bar_set_subtitle (header, _ ("Mind-Mapping Application"));
#line 14 "/home/trevorw/projects/Minder/src/minder.vala"
	gtk_header_bar_set_show_close_button (header, TRUE);
#line 16 "/home/trevorw/projects/Minder/src/minder.vala"
	_tmp1_ = (GtkApplicationWindow*) gtk_application_window_new ((GtkApplication*) self);
#line 16 "/home/trevorw/projects/Minder/src/minder.vala"
	g_object_ref_sink (_tmp1_);
#line 16 "/home/trevorw/projects/Minder/src/minder.vala"
	app_window = _tmp1_;
#line 17 "/home/trevorw/projects/Minder/src/minder.vala"
	gtk_window_set_title ((GtkWindow*) app_window, _ ("Minder"));
#line 18 "/home/trevorw/projects/Minder/src/minder.vala"
	gtk_window_set_position ((GtkWindow*) app_window, GTK_WIN_POS_CENTER);
#line 19 "/home/trevorw/projects/Minder/src/minder.vala"
	gtk_window_set_default_size ((GtkWindow*) app_window, 600, 400);
#line 20 "/home/trevorw/projects/Minder/src/minder.vala"
	gtk_window_set_titlebar ((GtkWindow*) app_window, (GtkWidget*) header);
#line 21 "/home/trevorw/projects/Minder/src/minder.vala"
	gtk_container_set_border_width ((GtkContainer*) app_window, (guint) 2);
#line 22 "/home/trevorw/projects/Minder/src/minder.vala"
	g_signal_connect ((GtkWidget*) app_window, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
#line 29 "/home/trevorw/projects/Minder/src/minder.vala"
	_tmp2_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 2);
#line 29 "/home/trevorw/projects/Minder/src/minder.vala"
	g_object_ref_sink (_tmp2_);
#line 29 "/home/trevorw/projects/Minder/src/minder.vala"
	box = _tmp2_;
#line 42 "/home/trevorw/projects/Minder/src/minder.vala"
	gtk_container_add ((GtkContainer*) app_window, (GtkWidget*) box);
#line 43 "/home/trevorw/projects/Minder/src/minder.vala"
	gtk_widget_show_all ((GtkWidget*) app_window);
#line 45 "/home/trevorw/projects/Minder/src/minder.vala"
	gtk_widget_show ((GtkWidget*) app_window);
#line 9 "/home/trevorw/projects/Minder/src/minder.vala"
	_g_object_unref0 (box);
#line 9 "/home/trevorw/projects/Minder/src/minder.vala"
	_g_object_unref0 (app_window);
#line 9 "/home/trevorw/projects/Minder/src/minder.vala"
	_g_object_unref0 (header);
#line 132 "minder.c"
}


gint minder_main (gchar** args, int args_length1) {
	gint result = 0;
	Minder* app = NULL;
	Minder* _tmp0_;
	gchar** _tmp1_;
	gint _tmp1__length1;
	gint _tmp2_;
#line 51 "/home/trevorw/projects/Minder/src/minder.vala"
	_tmp0_ = minder_new ();
#line 51 "/home/trevorw/projects/Minder/src/minder.vala"
	app = _tmp0_;
#line 53 "/home/trevorw/projects/Minder/src/minder.vala"
	_tmp1_ = args;
#line 53 "/home/trevorw/projects/Minder/src/minder.vala"
	_tmp1__length1 = args_length1;
#line 53 "/home/trevorw/projects/Minder/src/minder.vala"
	_tmp2_ = g_application_run ((GApplication*) app, _tmp1__length1, _tmp1_);
#line 53 "/home/trevorw/projects/Minder/src/minder.vala"
	result = _tmp2_;
#line 53 "/home/trevorw/projects/Minder/src/minder.vala"
	_g_object_unref0 (app);
#line 53 "/home/trevorw/projects/Minder/src/minder.vala"
	return result;
#line 159 "minder.c"
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
#line 49 "/home/trevorw/projects/Minder/src/minder.vala"
	return minder_main (argv, argc);
#line 169 "minder.c"
}


static void minder_class_init (MinderClass * klass) {
#line 3 "/home/trevorw/projects/Minder/src/minder.vala"
	minder_parent_class = g_type_class_peek_parent (klass);
#line 3 "/home/trevorw/projects/Minder/src/minder.vala"
	((GApplicationClass *) klass)->activate = (void (*) (GApplication *)) minder_real_activate;
#line 178 "minder.c"
}


static void minder_instance_init (Minder * self) {
}


GType minder_get_type (void) {
	static volatile gsize minder_type_id__volatile = 0;
	if (g_once_init_enter (&minder_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MinderClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) minder_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Minder), 0, (GInstanceInitFunc) minder_instance_init, NULL };
		GType minder_type_id;
		minder_type_id = g_type_register_static (gtk_application_get_type (), "Minder", &g_define_type_info, 0);
		g_once_init_leave (&minder_type_id__volatile, minder_type_id);
	}
	return minder_type_id__volatile;
}



